apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frappe-lms-sites
  namespace: apptolast-frappe-lms
  labels:
    app: frappe-lms
    environment: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frappe-lms-logs
  namespace: apptolast-frappe-lms
  labels:
    app: frappe-lms
    environment: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-frappe-lms-data
  namespace: apptolast-frappe-lms
  labels:
    app: mariadb-frappe-lms
    environment: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
